[supervisord]
nodaemon=true
logfile=/dev/null
logfile_maxbytes=0

[program:web]
command=waitress-serve --host=0.0.0.0 --port=%(ENV_PORT)s web.app:app
directory=/opt/render/project/src
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:bot]
command=python bot/bot.py
directory=/opt/render/project/src
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
